# https://taskfile.dev

version: '3'

tasks:
  default:
    - task: cq

  cq:
    cmds:
      - task: lint
      - task: fmt

  lint:
    desc: run lint tasks
    ignore_error: true
    cmd: golangci-lint run --fix

  fmt:
    desc: run formatting tasks
    ignore_error: true
    cmd: gofumpt -w **/*.go

  install:
    desc: install current pkg to gobin
    cmd: go install .


